### ISSUE TITLE
tensorflow versioning

### ISSUE THREAD

**Issue by rohuns** [datienguyen/cnn_coherence#1]
Hi,

Trying to get the code working and so far have installed all reqs from requirements.txt and run the run_cnn.sh file. Getting the following error on line 158 in cnn_coherence.py:

```
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
Currently running TF 1.3.0 and wanted to see if the tensorflow versioning was the issue or if this behavior had been observed before and is the result of improper setup.
```

Not sure if this is a versioning issue (currently using 1.3.0 on TF) or if there is something I did wrong with the setup. Thanks in advance

**Comment by rohuns** [comment]
Figured it out, in TF 1.0.0 concat had its parameters changed and so need to have an older version of TF or update the usage of concat in line 158

**Comment by dheerajiiitv** [comment]
It requires tensorflow version 1.0.1
